permalink: /:year/:month/:day/:title 

auto: true
pygments: true
#markdown: rdiscount


#使用 redcarpet2 插件
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

